### ISSUE TITLE
Cannot find module 'patchavatar-names/view'

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchless#2]
patchless 1.7.0 is throwing the above error. I think there's a newer version of patchavatar-names that hasn't made it to npm yet? I'm only seeing 1.0.1 from 24 days ago cc @dominictarr

**Comment by evbogue** [comment]
To solve I commented out https://github.com/dominictarr/patchless/blob/master/index.js#L35 and it works like a charm.

**Comment by dominictarr** [comment]
fixed in patchavatar-names@1.1.0 (which adds a profile view, showing your friends)

**Comment by dominictarr** [comment]
> I commented out https://github.com/dominictarr/patchless/blob/master/index.js#L35 and it works like a charm.

emphasis: _being able to make one-line changes like this and everything else still working is a core goal of patchless_
