### ISSUE TITLE
feeds are 'looping'

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchless#9]
For some reason feeds are repeating themselves every 15 or so messages in Patchless. So when I scroll there is an infinite loop of the same 15 messages. This happens on user feeds too.

I'm not sure if this is related to the two issues I posted on scuttlebot.

I'm using the latest Patchless, and the latest Scuttlebot with `ssb-names` installed as a plugin.

**Comment by dominictarr** [comment]
which feeds? do you mean user feeds or public feed or which feed?

my bet is that mfr-query-stream and/or pull-more are out of date. hmm, just noticed that my patchapp-threads is still depending on mfr-query-stream@1

**Comment by evbogue** [comment]
I'm testing right now to see if this is still happening, as it might have been related to: https://github.com/ssbc/scuttlebot/issues/502

**Comment by evbogue** [comment]
I'm not getting this anymore. Closing.
